### ISSUE TITLE
LocalizeText.csvにおいてキーを追加してLocalizationEnumを再度生成すると、既に設定したキーがずれる

### ISSUE THREAD

**Issue by shuhei-yamada** [MasaKoha/Icarus#11]
再現手順
1.LocalizeText.csvを以下の内容にする
```
key,ja,en
key1,値1,Value1
key10,値10,Value10
```
2.Enumを生成し、インスペクターからKey10を選択する（実行すると値10と表示される）
3.LocalizeText.csvを以下の内容にする
```
key,ja,en
key1,値1,Value1
key2,値2,Value2
key10,値10,Value10
```
4.Enumを再生成する
5.実行すると値2と表示される

**Comment by MasaKoha** [comment]
https://www.urablog.xyz/entry/2018/05/21/081702
これを使って修正する必要がありそうですが、とりあえずこちらでは
UGUITextLoalize コンポーネントで Enum(Key) からテキストを取ってきたのを、string(Key) からテキストを取ってくるように v1.2.0 で修正します。
ありがとうございます！
